### ISSUE TITLE
RuntimeError: bool value of Variable objects containing non-empty torch.cuda.FloatTensor is ambiguous

### ISSUE THREAD

**Issue by FFFFFate-fjh** [Atcold/pytorch-MatchNet#3]
Hello, Atcold. First, thank you for issuing such a great program.
While I download the e-VDS35-m256-May17.tar and followed the steps that are posted on github to train a sample model for  MatchNet, the program crashed at the first epoch. 
Here is the stack from python.

`Traceback (most recent call last):
  File "main.py", line 402, in <module>
    main()
  File "main.py", line 195, in main
    train(train_loader, model, (mse, nll_final, nll_train), optimiser, epoch)
  File "main.py", line 305, in train
    ce_loss, mse_loss, state, x_hat_data = compute_loss(x[t], x[t + 1], y[t], state)
  File "main.py", line 265, in compute_loss
    (x_hat, state_), (_, idx) = model(V(x_), state_)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 225, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fung/workspace/pytorch-CortexNet/model/Model02.py", line 79, in forward
    s = state[layer - 1] or V(x.data.clone().zero_())
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/variable.py", line 122, in __bool__
    torch.typename(self.data) + " is ambiguous")
RuntimeError: bool value of Variable objects containing non-empty torch.cuda.FloatTensor is ambiguous
`

The error occurs at this line ` s= state[layer - 1] or V(x.data.clone().zero_())` , because it needs to combine the state.data and input x, after the first frame.  So, the program really crashed at `state[layer - 1]` .

I used the python3 to run the code and here is the command I used to run `python3 main.py --mode MatchNet --cuda | tee last/train.log`.  Also, the video data is in the default path.

So, what can I do to fix this error or something I missed or did wrong?

**Comment by FFFFFate-fjh** [comment]
Hi, I fix the problem by installing the pytorch from pip. The elder version of pytorch in my computer was complied by the source. 
I hope this can help with others who meet the same problem like me.
